### PR TITLE
Add prebuild library

### PR DESCRIPTION
**Pull request by renchenglei**
BACKGROUND: please refer to https://github.com/intel/external-mesa/pull/115
We encountered booting issue with previous patch. With @yugang's help, we added libglapi into prebuild library, now booting issue seems gone(just tried on GP and APL NUC).
This is a draft for the prebuild solution, I have checked the code under device/intel:
`broxton  build  common  elkhartlake  icelakeu  mixins  sepolicy`
Here broxton, icelakeu and elkhartlake should be the board target. And broxton(device/intel/broxton/AndroidProducts.mk) includes 3 lunch targets:
```
COMMON_LUNCH_CHOICES += \
    gordon_peak-userdebug \
    apl_nuc-userdebug \
    leaf_hill-userdebug
```
So this 3 lunch targets should have same library(especially vulkan). For this 3, we could use one prebuild library, which could help reduce the library number. I tried GP and APL NUC with one same library, and both could boot up.
For the 3 board targets, broxton and icelakeu take use of our mesa, elkhartlake may use aosp gfx driver(vendor/lib64/egl/):
`libEGL_swiftshader.so        libGLESv1_CM_swiftshader.so  libGLESv2_swiftshader.so`
From this patch, we only need some little modify for Android.mk. It will not be a risk for mesa rebase. I will have much more test for this changes before we accpet this. If there is any concern, please feel free to point out. :)
@tpalli & @strassek FYI.

### CODE REVIEW

**Comment by renchenglei** [comment]
Updated the patch, we copy the pre-built library according to TARGET BOARD. Now we only need keep one Android.prebuild.mk file.

**Comment by renchenglei** [comment]
Updated the patch, we copy the pre-built library according to TARGET BOARD. Now we only need keep one Android.prebuild.mk file.

**Comment by renchenglei** [comment]
@strassek & @YuanjunHuang  & @jennycao, could you help take review of this changes, we have local build, it could boot to UI, and work fine. If it is ok, could we merge this as INTERNAL changes? Thanks a lot!
CC @tpalli, :)

**Comment by renchenglei** [comment]
Is there any comments? Could we get this merged on github?
@js0701 & @YuanjunHuang and @jennycao

**Comment by jennycao** [comment]
LGTM

**Comment by strassek** [comment]
One thing I'd like to see are instructions for how to generate and checkin these binaries - could be added to our 'Readme.md'. Also, I need to check to see if we are even allowed to distribute binaries here.

**Comment by renchenglei** [comment]
> One thing I'd like to see are instructions for how to generate and checkin these binaries - could be added to our 'Readme.md'. Also, I need to check to see if we are even allowed to distribute binaries here.

@strassek, if this change is ok, I will help generate the binaries every time after rebase. In fact, I generated those binaries based on 1A code.

**Comment by strassek** [comment]
Unfortunately we don't have permission to host the binaries in this repo, we can still land the build script changes (and any useful tooling). I'm asking for instructions so I can validate that this still works on my end after rebase.

**Comment by renchenglei** [comment]
As most of time we would build binary from source code instead of copy binary to image, it will be a little complex for maintain one build script. I will sync with other guys if we could keep those binary on other place. 
We have a try based on 19.0.x, the changes is huge:
https://github.com/intel/external-mesa/pull/115/commits/bdf98e2554043278ae66d26baa2f0a389a76c7ef
https://github.com/intel/external-mesa/pull/115/commits/9077a85d5309108ec198e261a1fee80292da4c88
https://github.com/intel/external-mesa/pull/115/commits/4f8362bb42f02bf59ccc671498e94459d1d1b964
https://github.com/intel/external-mesa/pull/115/commits/6e421e2c2b0e93e84e3b7cf0d1182e7786f1949a
https://github.com/intel/external-mesa/pull/115/commits/525b9b6389b324a39161ee309fae3ead4c2be229

**Comment by strassek** [comment]
@renchenglei During rebase I now see link errors like this:
```
ld.lld: error: duplicate symbol: build_id_data
>>> defined at build_id.c:132 (hardware/intel/external/mesa3d-intel/src/util/build_id.c:132)
>>>            build_id.o:(build_id_data) in archive out/target/product/celadon_ivi/obj/STATIC_LIBRARIES/libmesa_util_intermediates/libmesa_util.a
>>> defined at build_id.c:132 (hardware/intel/external/mesa3d-intel/src/util/build_id.c:132)
>>>            build_id.o:(.text.build_id_data+0x0) in archive out/target/product/celadon_ivi/obj/STATIC_LIBRARIES/libmesa_vulkan_common_intermediates/libmesa_vulkan_common.a
```
I assume this is related? Can you provide instructions for building from source?

**Comment by renchenglei** [comment]
@strassek, on Celadon, we didn't add prebuild library. I pull latest upstream master code, and build on Android directly. This issue can not be reproduced. Could you share which version are you working on rebase?

**Comment by strassek** [comment]
@renchenglei I was working on a 19.1.7 rebase, at this point. I may opt to move directly to 19.2 if these issues are not present.
